# Generated by Django 5.1.1 on 2024-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='src/default.jpg', upload_to='src/'),
        ),
    ]
