# Generated by Django 5.1.1 on 2024-09-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registrar', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='media/src/default.jpg', upload_to='media/src/'),
        ),
    ]
